ducter-dev/SCADA

src/modules/dashboard/views/Dashboard.vue
src/modules/tanques/composables/useTanqueEspera.js
src/modules/tanques/views/EntradaManual.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/zM23ziSNQlesGfpBHHSPog?src=GitHub) by ducter-dev on Jan 17, 2023
[SIN-43 Revisión de workflow de procesos de SCADA](https://ducter-development.atlassian.net/browse/SIN-43)  

SIN-43 :sparkles: Completa función agregar autotanque a lista de espera.

---

src/modules/tanques/views/EntradaManual.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/Pd_IgTIxTVyicv3LSSk0lQ?src=GitHub) by ducter-dev on Jan 17, 2023
[SIN-44 Agregar tanque a lista de espera](https://ducter-development.atlassian.net/browse/SIN-44)  

SIN-44 :sparkles: Agregada función de agregar tanques a lista de espera.

---

src/modules/dashboard/components/TarjetaAsignacion.vue
src/modules/dashboard/views/Dashboard.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/1CxVs2ckRnqT7RY4MXDs0Q?src=GitHub) by ducter-dev on Jan 18, 2023
[SIN-46 Revisión del workflow de proceso de asignación](https://ducter-development.atlassian.net/browse/SIN-46)  

SIN-46 :contruction: Revisando workflow de asignación.

---

src/modules/dashboard/views/Dashboard.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/B9azduEBRBWTADNi-g0Yxw?src=GitHub) by ducter-dev on Jan 18, 2023
[SIN-55 Encontrar las llenaderas disponible](https://ducter-development.atlassian.net/browse/SIN-55)  

SIN-55 :construction: Ya se obitnen las llenaderas disponibles.

---

src/modules/dashboard/components/SideBar.vue
src/modules/dashboard/views/Configuracion.vue
src/modules/tanques/components/TableTanques.vue
src/modules/tanques/composables/useLlenaderas.js
src/modules/tanques/composables/useTanque.js
src/modules/tanques/store/tanquesStore.js
src/modules/tanques/views/Tanques.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/GTGRnB5RThiRbuT7Af5PdA?src=GitHub) by ducter-dev on Jan 18, 2023
[SIN-56 Registrar autotanque tanque](https://ducter-development.atlassian.net/browse/SIN-56)  

SIN-56 :fire: Obteniendo registros y guardando autotanque de manera manual.

---

package-lock.json
package.json
src/index.css
src/main.js
src/modules/auth/views/Login.vue
src/modules/dashboard/components/TarjetaAsignacion.vue
src/modules/dashboard/views/Dashboard.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/ACX5jPoHSKafumxsoJb2Eg?src=GitHub) by ducter-dev on Feb 24, 2023
[SIN-60 Cambiar diseño etiqueta Asignación - Agregar botones de asignación](https://ducter-development.atlassian.net/browse/SIN-60)  

sin-60 cambio de diseño de etiqueta de botonera

---

src/assets/icons/circle.svg
src/modules/dashboard/components/TarjetaAsignacion.vue
src/modules/dashboard/composables/useDashboard.js
src/modules/dashboard/store/dashboardStore.js
src/modules/dashboard/views/Dashboard.vue

Agregada funcionalidad al botón de siguiente llenadera
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/PBYPe5wQSWy5zEFCMXj7lg?src=GitHub) by ducter-dev on Feb 24, 2023
[SIN-61 Dar funcionalidad a botón Siguiente Llenadera](https://ducter-development.atlassian.net/browse/SIN-61)  

sin-61 Funcionalidad siguiente llenadera

---

src/modules/dashboard/components/TarjetaAsignacion.vue
src/modules/dashboard/composables/useDashboard.js
src/modules/dashboard/store/dashboardStore.js
src/modules/dashboard/views/Dashboard.vue

Se agrego la funcionalidad de comunicación con API de reasignar asignación, y se agrego validación de respuesta de errores.
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/heR4_vMJQ36yHQdowBrl7Q?src=GitHub) by ducter-dev on Feb 27, 2023
[SIN-64 Dar funcionalidad a botón Reasignar Asignación](https://ducter-development.atlassian.net/browse/SIN-64)  

SIN-64 funcionalidad a botón reasignar

---

src/modules/dashboard/components/TarjetaAsignacion.vue
src/modules/dashboard/composables/useDashboard.js
src/modules/dashboard/store/dashboardStore.js
src/modules/dashboard/views/Dashboard.vue

Se agrego funcionalidad al botón de cancelar la asignación.
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/0vfJp2kRQCiKtavo4vcNZw?src=GitHub) by ducter-dev on Feb 27, 2023
[SIN-63 Dar funcionalidad a botón Cancela Asignación](https://ducter-development.atlassian.net/browse/SIN-63)  

SIN-63 función a botón de cancelar asignación

---

src/layout/components/Breadcrumb/Index.vue
src/layout/components/Card/CardListItem.vue
src/layout/components/Sidebar/Secondary.vue
src/modules/auth/store/login.js
src/modules/dashboard/components/TarjetaAsignacion.vue
src/modules/dashboard/components/WaitingList.vue
src/modules/dashboard/router/index.js
src/modules/dashboard/views/Dashboard.vue
src/modules/services/views/index.vue

Se agrego lista de servicios en vista aparte 
Se agrego correción en componentes
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/x8d1n6EmT6y7tBoshVTbmw?src=GitHub) by ducter-dev on Mar 2, 2023
[SIN-78 Obtener información y llenar tabla de servicios](https://ducter-development.atlassian.net/browse/SIN-78)  

SIN-78 se agrego la vista de servicios

---

src/modules/dashboard/components/InputAntenna.vue
src/modules/dashboard/components/TarjetaUltimasCargas.vue
src/modules/dashboard/components/WaitingList.vue
src/modules/dashboard/components/toast/item.vue
src/modules/dashboard/views/Dashboard.vue

Se agrego componente para antena de entrada.
Se agrego indicador de error en notificaciones toast para su depuración de errores
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/srfVG53qSgWzrVnLBF2wGw?src=GitHub) by efren.colin on Mar 2, 2023
[SIN-71 Obtener información y llenar tarjeta de la barrera de entrada](https://ducter-development.atlassian.net/browse/SIN-71)  

SIN-71 tarjeta de entrada

---

src/modules/dashboard/components/AntennaVerifcation.vue
src/modules/dashboard/views/Dashboard.vue

Se agrego funcionalidad a la tarjeta de antena de verificación
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/gUlHDe6ZQAy0rF6TVedRMA?src=GitHub) by efren.colin on Mar 2, 2023
[SIN-72 Obtener información y llenar tarjeta de la barrera de verificación](https://ducter-development.atlassian.net/browse/SIN-72)  

SIN-72 tarjeta de antena de verifiación

---

src/modules/dashboard/components/OutputAntenna.vue
src/modules/dashboard/views/Dashboard.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/_UbAZXfgS-2KsF3pEYsNlg?src=GitHub) by efren.colin on Mar 2, 2023
[SIN-73 Obtener información y llenar tarjeta de la barrera de salida](https://ducter-development.atlassian.net/browse/SIN-73)  

SIN-73 Tarjeta de antena de salida

---

src/layout/components/Form/FloatInput.vue
src/modules/dashboard/components/LastEntry.vue
src/modules/dashboard/components/WaitingList.vue
src/modules/dashboard/views/Dashboard.vue
src/modules/entries/components/create.vue

Se conecto componente de última entrada con endpointde API
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/Io0phTthRW6MsXa9PC43oQ?src=GitHub) by ducter-dev on Mar 6, 2023
[SIN-74 Obtener información y llenar tarjeta de la última entrada](https://ducter-development.atlassian.net/browse/SIN-74)  

SIN-74 obtener info en componente

---

src/modules/dashboard/components/LastOutput.vue
src/modules/dashboard/views/Dashboard.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/0Du7gM2iRm2qK4KiegVkrg?src=GitHub) by efren.colin on Mar 6, 2023
[SIN-76 Obtener información y llenar tarjeta de la última salida](https://ducter-development.atlassian.net/browse/SIN-76)  

SIN-76 componente agregado

---

src/modules/tanques/components/TableEspera.vue
src/modules/tanques/composables/useTanqueEspera.js
src/modules/tanques/store/tanquesStore.js

Se agrego funcionalidad de mover un eleemento en la tabla de espera
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/SuyIbk1ySTeaBVICA71Nrg?src=GitHub) by efren.colin on Mar 9, 2023
[SIN-80 Realizar función de mover un tanque en la lista de espera](https://ducter-development.atlassian.net/browse/SIN-80)  

SIN-80 mover elemento de tabla de espera

---

src/modules/dashboard/components/WaitingList.vue
src/modules/dashboard/views/Dashboard.vue
src/modules/entries/components/create.vue
src/modules/tanques/components/TableEspera.vue
src/modules/tanques/composables/useTanqueEspera.js
src/modules/tanques/store/tanquesStore.js

Se agregan cambios para mostrar información en la tarjeta de asignación.
Se agrega correción en modal de crear entradas.
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/3bYPuhQxQtaxzH5zE3XVaw?src=GitHub) by efren.colin on Mar 9, 2023
[SIN-75 Obtener información y llenar tarjeta de la última asignación](https://ducter-development.atlassian.net/browse/SIN-75)  

SIN-75 Cambios realizados en asignación

---

src/layout/components/Sidebar/Secondary.vue
src/modules/dashboard/router/index.js
src/modules/entries/views/index.vue
src/modules/tanques/components/TableEspera.vue

Mostrar seccion de Lista de espera.
Cambiar tipo en la tabla  de lista de espera
Cambiar tipo en la tabla de la lista de entrada
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/SjMcLAiRR6CG_EuR_s9xNA?src=GitHub) by ducter-dev on Mar 17, 2023
[SIN-88 Mostrar Sección Espera](https://ducter-development.atlassian.net/browse/SIN-88)  

sin-88 Mostar seccion espera

---

src/modules/auth/router/index.js
src/modules/auth/views/ResetPassword.vue

Agregar vistas de formulario contraseña
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/DNX9DpexQiivnQtFjl67SQ?src=GitHub) by ducter-dev on Mar 21, 2023
[SIN-102 Creación de formulario de actualización de password](https://ducter-development.atlassian.net/browse/SIN-102)  

sin-102 formulario de contrasena

---

src/modules/auth/router/index.js
src/modules/auth/views/RescutePassword.vue
src/modules/auth/views/ResetPassword.vue

Formulario de recuperacion de contraseña
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/HCOJ0R0OTf2m4mybGiYd0w?src=GitHub) by ducter-dev on Mar 22, 2023
[SIN-103 Creación de formulario de recuperar password](https://ducter-development.atlassian.net/browse/SIN-103)  

sin-103 formulario de recuperacion de contrasena

---

src/modules/auth/composables/useAuth.js
src/modules/auth/store/login.js
src/modules/auth/views/Login.vue

Bloquear usuario
[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/jVr6ndXPRl6p2FnWeqEJnw?src=GitHub) by ducter-dev on Mar 23, 2023
[SIN-104 Agregar funcionalidad de bloquear usuario](https://ducter-development.atlassian.net/browse/SIN-104)  

sin-104funcion de bloquear

---

src/modules/dashboard/views/Dashboard.vue
src/modules/entries/components/create.vue
src/modules/tanques/views/Nuevo.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/RV1U-OfnR32ikXq_WOGvPA?src=GitHub) by ducter-dev on Apr 19, 2023
[SIN-98 Obtener información de tanque al actualizar el nombre del tanque formulario entrada manual](https://ducter-development.atlassian.net/browse/SIN-98)  

SIN-98 :sparkles: Obtener la información de un tanque ya registrado.

---

src/modules/reports/components/FilterCard.vue
src/modules/reports/components/MensualesCard.vue
src/modules/reports/views/index.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/zCH-UWFEQp6MXBbN-Yl1Tg?src=GitHub) by ducter-dev on Apr 20, 2023
[SIN-145 Actualización de sección de Reportes](https://ducter-development.atlassian.net/browse/SIN-145)  

SIN-145 :sparkles: Arreglada seccion de reportes

---

src/modules/reports/components/FilterCard.vue
src/modules/reports/composables/useReportes.js

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/RERibmfTQFyaYNM-svLjYg?src=GitHub) by ducter-dev on Apr 20, 2023
[SIN-147 Agregar funcionalidad para descargar Reporte de Esferas](https://ducter-development.atlassian.net/browse/SIN-147)  

sin-147 Agregada función para decargar reportes de esferas infidividuales

---

src/modules/reports/components/FilterCard.vue
src/modules/reports/composables/useReportes.js

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/dAXekavQTR2Ndp5paV7ieQ?src=GitHub) by ducter-dev on Apr 20, 2023
[SIN-152 Agregar funcionalidad para descargar reporte de Patines (Frontend)](https://ducter-development.atlassian.net/browse/SIN-152)  

sin-152 :sparkles: Agregada función para descargar reportes de Patines individuales.

---

src/modules/reports/components/FilterCard.vue
src/modules/reports/composables/useReportes.js

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/E-57MWjVR3axSpD59Uclmg?src=GitHub) by ducter-dev on Apr 20, 2023
[SIN-154 Agregar funcionalidad para descargar reporte de Cromatógrafo (Frontend)](https://ducter-development.atlassian.net/browse/SIN-154)  

sin-154 :sparkles: Agregar función para dercargar archivo de cromatógrafo.

---

src/modules/reports/components/FilterCard.vue
src/modules/reports/composables/useReportes.js

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/hU4-d2JpRJedYftm2juC8Q?src=GitHub) by ducter-dev on Apr 20, 2023
[SIN-156 Agregar funcionalidad para descargar reporte de Bombas (Frontend)](https://ducter-development.atlassian.net/browse/SIN-156)  

sin-156 :sparkles: Creada función para descargar reporte de bombas.

---

src/modules/bitacora/composables/index.js
src/modules/bitacora/store/bitacora.js
src/modules/bitacora/views/index.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/sZAV2QCsQAyekvokpzO7mw?src=GitHub) by ducter-dev on Apr 21, 2023
[SIN-161 Agregar sección Bitácora en el Frontend](https://ducter-development.atlassian.net/browse/SIN-161)  

sin-161 :sparkles: Integrada sección bitácora

---

src/layout/components/Card/CardListActionButton.vue
src/layout/components/Header/Index.vue
src/modules/auth/composables/useAuth.js
src/modules/bitacora/composables/index.js
src/modules/bitacora/store/bitacora.js
src/modules/bitacora/views/index.vue
src/modules/dashboard/components/LastEntry.vue
src/modules/dashboard/components/LastOutput.vue
src/modules/dashboard/components/WaitingList.vue
src/modules/dashboard/store/dashboardStore.js
src/modules/dashboard/views/Dashboard.vue
src/modules/entries/components/create.vue
src/modules/reports/components/FilterCard.vue
src/modules/tanques/composables/useTanqueEspera.js
src/modules/tanques/store/tanquesStore.js
src/modules/tanques/views/Espera.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/iU5SXt8gTSSsS35y7PuWNA?src=GitHub) by ducter-dev on Apr 24, 2023
[SIN-160 Agregar eventos del frontend a bitácora de eventos](https://ducter-development.atlassian.net/browse/SIN-160)  

SIN-160 Agregar eventos del frontend a bitácora de eventos

---

src/modules/dashboard/components/WaitingList.vue
src/modules/tanques/components/TableEspera.vue
src/modules/tanques/composables/useTanqueEspera.js
src/modules/tanques/store/tanquesStore.js

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/dIzU5jz8TtOZR9NxLQwCqA?src=GitHub) by ducter-dev on Apr 28, 2023
[SIN-169 Agregar funcionalidad a botón de llamar tanque](https://ducter-development.atlassian.net/browse/SIN-169)  

sin-169 :sparkles: Agregando función de llamar tanque.

---

src/modules/tanques/components/TableEspera.vue
src/modules/tanques/store/tanquesStore.js

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/MHdCtm1NTJC2i1KE9VE32A?src=GitHub) by ducter-dev on Apr 28, 2023
[SIN-170 Agregar funcionalidad de eliminar tanque de la lista de espera](https://ducter-development.atlassian.net/browse/SIN-170)  

sin-170 :sparkles: Agreando funcionalidad para eliminar tanque de la lista de espera.

---

src/layout/components/Modal/Delete.vue
src/layout/composables/index.js
src/modules/dashboard/components/WaitingList.vue
src/modules/tanques/components/TableEspera.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/5rk6aI7ATlGkjbd17FVn3g?src=GitHub) by ducter-dev on May 1, 2023
[SIN-171 Revisar funcionalidad de botones de menú asignación](https://ducter-development.atlassian.net/browse/SIN-171)  

SIN-171 :sparkles: Revisados botones de menu asignación.

---

src/modules/usuarios/components/CreateUser.vue
src/modules/usuarios/components/EditUser.vue
src/modules/usuarios/components/Table.vue
src/modules/usuarios/composables/useUser.js
src/modules/usuarios/store/usuarioStore.js
src/modules/usuarios/views/Usuarios.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/xPSxBWhgTH2t6A8a2VT2MQ?src=GitHub) by ducter-dev on May 2, 2023
[SIN-173 Editar usaurio](https://ducter-development.atlassian.net/browse/SIN-173)  

sin-173 :sparkles: Agregada funcion de editar usuario.

---

src/modules/usuarios/components/Table.vue
src/modules/usuarios/views/Usuarios.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/zeuy0YcLTbWd7-02xmOCQw?src=GitHub) by ducter-dev on May 2, 2023
[SIN-175 Eliminar usuario](https://ducter-development.atlassian.net/browse/SIN-175)  

SIN-175 Eliminar usuario

---

src/modules/entries/components/create.vue
src/modules/tanques/components/EditTankWaitingList.vue
src/modules/tanques/components/TableEspera.vue
src/modules/tanques/composables/useTanqueEspera.js
src/modules/tanques/store/tanquesStore.js
src/modules/usuarios/components/EditUser.vue

[Changes reviewed on CodeStream](https://api.codestream.com/r/YbPM4gTeRRLdpfdq/IuIGAaaTRUSZIjCIBiT-aA?src=GitHub) by ducter-dev on May 2, 2023
[SIN-172 Editar Tanque en lista de espera](https://ducter-development.atlassian.net/browse/SIN-172)  

sin-172 :sparkles: Editar tanque de lista de espera actualizado.

---

src/modules/dashboard/components/AntennaVerifcation.vue
src/modules/dashboard/components/InputAntenna.vue
src/modules/dashboard/components/LastEntry.vue
src/modules/dashboard/components/LastOutput.vue
src/modules/dashboard/components/OutputAntenna.vue
src/modules/dashboard/components/WaitingList.vue
src/modules/dashboard/composables/useDashboard.js
src/modules/dashboard/store/dashboardStore.js
src/modules/dashboard/views/Dashboard.vue
src/modules/entries/components/create.vue
src/modules/tanques/components/TableEspera.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/rWib05aVRS2pBKQouLMB2A?src=GitHub) by ducter-dev on May 17, 2023
[SIN-183 Corrección de registro de entrada](https://ducter-development.atlassian.net/browse/SIN-183)  

sin-184 Corregido formulario de entradas y corregidas rutas de abtenas y barreras.

---

src/modules/reports/components/FilterCard.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/tM70JKeVReCvwtikaF9U_g?src=GitHub) by ducter-dev on May 18, 2023
[SIN-187 Agregar funcionalidad para obtener reportes de 24 y 05 horas (Fronted)](https://ducter-development.atlassian.net/browse/SIN-187)  

SIN-187 :zap: Agregar funcionalidad para obtener reportes de 24 y 05 horas (Fronted)

---

src/modules/reports/components/FilterCard.vue
src/modules/reports/composables/useReportes.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/_XjXcDWURH6XuVPvFN42EA?src=GitHub) by ducter-dev on May 19, 2023
[SIN-188 Agregar rutas de reportes pendientes (Frontend)](https://ducter-development.atlassian.net/browse/SIN-188)  

SIN-188 :zap: Agregar rutas de reportes pendientes (Frontend) 

---

src/modules/reports/components/FilterCard.vue
src/modules/reports/composables/useReportes.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/3eIoUzKeT3yaQbYHFriuMg?src=GitHub) by ducter-dev on May 23, 2023
[SIN-158 Agregar funcionalidad para descargar reporte de Balances Diario (Frontend)](https://ducter-development.atlassian.net/browse/SIN-158)  

sin-158 Creada función para descargar reporte de balance diario.

---

src/modules/dashboard/components/AntennaVerifcation.vue
src/modules/dashboard/components/InputAntenna.vue
src/modules/dashboard/components/OutputAntenna.vue
src/modules/dashboard/components/TarjetaUltimasCargas.vue
src/modules/tanques/composables/useTanqueSalida.js
src/modules/tanques/store/tanquesStore.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/zU-vFxTUQWK9_lY53Ojhfg?src=GitHub) by ducter-dev on May 25, 2023
[SIN-205 Crear función para generar reporte de densidades](https://ducter-development.atlassian.net/browse/SIN-205)  

SIN-205 Crear función para generar reporte de densidades

---

src/modules/reports/components/FilterCard.vue
src/modules/reports/composables/useReportes.js
src/modules/tanques/composables/useTanqueSalida.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/TZpFWyXjReevt6Jb-O5Xiw?src=GitHub) by ducter-dev on May 25, 2023
[SIN-206 Agregar funcionalidad para descargar reporte de densidades (Frontend)](https://ducter-development.atlassian.net/browse/SIN-206)  

sin-206 :sparkles: Agregada función para descargar reporte de densidades

---

src/modules/reports/components/MensualesCard.vue
src/modules/reports/composables/useReportes.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/7gxMWZpXTfCniUXk4n6CLQ?src=GitHub) by ducter-dev on May 26, 2023
[SIN-200 Agregar funcionalidad para descargar reporte de cromatógafo mensual (Frontend)](https://ducter-development.atlassian.net/browse/SIN-200)  

sin -200 :sparkles: Agregada función para descargar reportes mnsuales del cromatógrafo.

---

package-lock.json
src/modules/reports/components/FilterCard.vue
src/modules/reports/components/MensualesCard.vue
src/modules/reports/views/index.vue
src/modules/tanques/components/TableTanques.vue
src/modules/tanques/views/Tanques.vue
src/modules/usuarios/views/Usuarios.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/5oelJgewR_iEcdk4ADuj6w?src=GitHub) by ducter-dev on Jun 26, 2023
[SIN-221 Corregir colores de pantalla de reportes modo nocturno](https://ducter-development.atlassian.net/browse/SIN-221)  

sin-221 Agregada modo dark en reportes y configuración.

---

src/modules/dashboard/components/TarjetaAsignacion.vue
src/modules/dashboard/components/WaitingList.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/3evaSZUqTwiOvrnPDF3CWQ?src=GitHub) by ducter-dev on Jun 26, 2023
[SIN-222 Quitar advertencias de botonera de menu de asignación](https://ducter-development.atlassian.net/browse/SIN-222)  

sin-122 :zap: Quitando advertencias de botonera de menu

---

src/modules/dashboard/components/LastEntry.vue
src/modules/dashboard/components/LastOutput.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/aEoUaXukQ8-5nOq3xcakmg?src=GitHub) by ducter-dev on Jun 26, 2023
[SIN-223 Quitar advertencias de las barreras.](https://ducter-development.atlassian.net/browse/SIN-223)  

sin-223 :zap: se quitaron leyendas de error de barreras de veificiación.

---

src/modules/dashboard/layouts/DashboardLayout.vue
src/modules/dashboard/views/Dashboard.vue
src/modules/tanques/components/FormTanque.vue
src/modules/tanques/composables/useTanque.js
src/modules/tanques/router/index.js
src/modules/tanques/store/tanquesStore.js
src/modules/tanques/views/Create.vue
src/modules/tanques/views/Edit.vue
src/modules/tanques/views/Editar.vue
src/modules/tanques/views/Index.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/VdMheiGKSl6iZk3bzUU7iQ?src=GitHub) by ducter-dev on Aug 7, 2023
[SIN-174 Editar Tanque](https://ducter-development.atlassian.net/browse/SIN-174)  

SIN-174 Editar Tanque

---

src/modules/tanques/composables/useTanque.js
src/modules/tanques/store/tanquesStore.js
src/modules/tanques/views/Index.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/udEbC-9BQ_ihjxm-TYDdHQ?src=GitHub) by ducter-dev on Aug 7, 2023
[SIN-230 Agregar filtro de Tanques](https://ducter-development.atlassian.net/browse/SIN-230)  

:sparkles: Filtrado terminado

---

src/modules/usuarios/components/CreateUser.vue
src/modules/usuarios/store/usuarioStore.js
src/modules/usuarios/views/Register.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/H5-yFGpkQOeybIvJTtYlWQ?src=GitHub) by ducter-dev on Aug 8, 2023
[SIN-238 Modificar registro de usuarios](https://ducter-development.atlassian.net/browse/SIN-238)  

SIN-238 Modificar registro de usuarios

---

src/modules/auth/composables/useAuth.js
src/modules/auth/store/login.js
src/modules/auth/views/Login.vue
src/modules/auth/views/RescutePassword.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/NTQXc7XPRKaCx1eecJjXqQ?src=GitHub) by ducter-dev on Aug 9, 2023
[SIN-240 Crear formulario en el frontend](https://ducter-development.atlassian.net/browse/SIN-240)  

SIN-240 Crear formulario en el frontend

---

src/modules/auth/store/login.js
src/modules/auth/views/Login.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/iUZFaMHnTvSgIQnA35B6zQ?src=GitHub) by ducter-dev on Aug 9, 2023
[SIN-243 Validar en el frontend la caducidad de password](https://ducter-development.atlassian.net/browse/SIN-243)  

SIN-243 Validar en el frontend la caducidad de password

---

src/modules/auth/views/ResetPassword.vue
src/modules/reports/components/MensualesCard.vue
src/modules/reports/composables/useReportes.js

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/iBeEnLwgRF6IbblfjHYYZg?src=GitHub) by ducter-dev on Aug 18, 2023
[SIN-250 Añadir al frontend enlace para reporte de balance mensual ](https://ducter-development.atlassian.net/browse/SIN-250)  

SIN-250 Añadir al frontend enlace para reporte de balance mensual 

---

src/layout/components/Header/Index.vue
src/layout/components/Sidebar/Secondary.vue
src/modules/auth/router/index.js
src/modules/auth/store/login.js
src/modules/dashboard/components/SideBar.vue
src/modules/dashboard/components/WaitingList.vue
src/modules/dashboard/layouts/DashboardLayout.vue
src/modules/dashboard/views/Dashboard.vue
src/modules/entries/components/create.vue
src/modules/entries/views/index.vue
src/modules/tanques/components/TableEspera.vue
src/router.js
src/views/Landing.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/2fbVK8jnQzienU4bZfbn5A?src=GitHub) by ducter-dev on Aug 23, 2023
[SIN-254 Agregar validación de permisos para vistas por perfiles de usuarios](https://ducter-development.atlassian.net/browse/SIN-254)  

SIN-254 Agregar validación de permisos para vistas por perfiles de usuarios

---

src/modules/auth/views/RescutePassword.vue
src/modules/dashboard/layouts/DashboardLayout.vue
src/modules/entries/components/create.vue
src/modules/tanques/components/EditTankWaitingList.vue
src/modules/tanques/components/FormTanque.vue
src/modules/tanques/components/TableEspera.vue
src/modules/tanques/views/Create.vue
src/modules/tanques/views/Edit.vue
src/modules/usuarios/views/Create.vue
src/modules/usuarios/views/Edit.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/7XGoHUnFRBmzM81FC86Umw?src=GitHub) by ducter-dev on Aug 24, 2023
[SIN-255 Visualizar botón de agregar entradas](https://ducter-development.atlassian.net/browse/SIN-255)  

SIN-255 Visualizar botón de agregar entradas

---

index.html
src/modules/entries/components/create.vue

[Changes reviewed on CodeStream](https://codestream-us1.service.newrelic.com/r/YbPM4gTeRRLdpfdq/dTbv-sCHSH-hA9MFmsSwRg?src=GitHub) by ducter-dev on Sep 5, 2023
[SIN-256 Cambiar el título de la aplicación en las páginas](https://ducter-development.atlassian.net/browse/SIN-256)  

SIN-256 Cambiar el título de la aplicación en las páginas
